### ISSUE TITLE
upsample layer problem

### ISSUE THREAD

**Issue by trminh89** [alexgkendall/caffe-segnet#10]
Hi @alexgkendall ,

My data have 8 classes, when I change the number of class in the model file, I had this problem. Can you please have a look at my segnet_basic_train.prototxt file (http://pastebin.com/8SFwqtij) and show me what's wrong?

Thanks!

F1125 15:28:05.204437 5212 upsample_layer.cpp:63] Check failed: bottom[0]->height() == bottom[1]->height() (59 vs. 60)
**\* Check failure stack trace: ***
@ 0x7f7bf11c3daa (unknown)
@ 0x7f7bf11c3ce4 (unknown)
@ 0x7f7bf11c36e6 (unknown)
@ 0x7f7bf11c6687 (unknown)
@ 0x7f7bf1557af9 caffe::UpsampleLayer<>::Reshape()
@ 0x7f7bf15f3f07 caffe::Net<>::Init()
@ 0x7f7bf15f5cb2 caffe::Net<>::Net()
@ 0x7f7bf14ecb00 caffe::Solver<>::InitTrainNet()
@ 0x7f7bf14edbe3 caffe::Solver<>::Init()
@ 0x7f7bf14eddb6 caffe::Solver<>::Solver()
@ 0x40edf0 caffe::GetSolver<>()
@ 0x408683 train()
@ 0x406c81 main
@ 0x7f7bf06d5ec5 (unknown)
@ 0x40722d (unknown)
@ (nil) (unknown)
Aborted (core dumped)

**Comment by trminh89** [comment]
I have fixed the problem with upsample_param. Thanks anyway!

**Comment by alexgkendall** [comment]
Hi @trminh89 ,

Great to hear you have solved it - the issue is that your data has different input dimensions to the example. You need to modify the upsample_param to match your dataset's pooling dimensions.

Alex

**Comment by minemeraj** [comment]
I0609 12:45:05.614660 19851 layer_factory.hpp:74] Creating layer relu5_1_D
I0609 12:45:05.614670 19851 net.cpp:90] Creating Layer relu5_1_D
I0609 12:45:05.614680 19851 net.cpp:410] relu5_1_D <- conv5_1_D
I0609 12:45:05.614693 19851 net.cpp:357] relu5_1_D -> conv5_1_D (in-place)
I0609 12:45:05.614704 19851 net.cpp:120] Setting up relu5_1_D
I0609 12:45:05.614715 19851 net.cpp:127] Top shape: 1 512 23 30 (353280)
I0609 12:45:05.614723 19851 layer_factory.hpp:74] Creating layer upsample4
I0609 12:45:05.614738 19851 net.cpp:90] Creating Layer upsample4
I0609 12:45:05.614747 19851 net.cpp:410] upsample4 <- conv5_1_D
I0609 12:45:05.614760 19851 net.cpp:410] upsample4 <- pool4_mask
I0609 12:45:05.614773 19851 net.cpp:368] upsample4 -> pool4_D
I0609 12:45:05.614786 19851 net.cpp:120] Setting up upsample4
F0609 12:45:05.614822 19851 upsample_layer.cpp:63] Check failed: bottom[0]->height() == bottom[1]->height() (23 vs. 17) 

Anyone can tell me how to determine the height and weight of the unSampling?
I am using 210 \* 260 pixel images.

**Comment by gaurav16gupta** [comment]
Hi @minemeraj 
If you got the answer, please let me know how to determine the height and weight of the unSampling?

**Comment by hkaraoguz** [comment]
VGG16's last convolutional layer has a feature map that is 1/16 of the original input image size. You can calculate the required parameters by dividing the original image's width and height by 16 and using the ceiling function if there is a remainder. For 210x260 it should be 14x17.

**Comment by imransalam** [comment]
@trminh89 , Hi. 
Where is the upsample_param? My error is raised from upsample_layer.cpp (line 63) of the caffe-segnet. The solver I am using is SegNet/Models/segnet_solver.prototxt.

**Comment by cchenzhou** [comment]
@alexgkendall ，Hi,
I do not know how to modify the upsample_param ? can you tell me  ? thank you.

**Comment by cchenzhou** [comment]
I know how to modify the upsample_param,modify the upsample_w and upsample_h in the train.prototxt.
