### ISSUE TITLE
Check failed: bottom[0]->height() == bottom[1]->height() (23 vs. 15) 

### ISSUE THREAD

**Issue by adaxidedakaonang** [alexgkendall/caffe-segnet#110]
I'm sorry for bothering you. This is the same question which bothering me. I need to know that how should I fix this problem. Maybe I should write new value to upsample_w and upsample_h， and I want to know 'how'. I'm new to caffe . Grateful for Alex.

F0506 13:02:49.495620  8091 upsample_layer.cpp:59] Check failed: bottom[0]->height() == bottom[1]->height() (23 vs. 15) 
*** Check failure stack trace: ***
    @     0x7f553c1cb5cd  google::LogMessage::Fail()
    @     0x7f553c1cd433  google::LogMessage::SendToLog()
    @     0x7f553c1cb15b  google::LogMessage::Flush()
    @     0x7f553c1cde1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f553c937edb  caffe::UpsampleLayer<>::Reshape()
    @     0x7f553c803301  caffe::Net<>::Init()
    @     0x7f553c804b81  caffe::Net<>::Net()
    @     0x7f553c99156a  caffe::Solver<>::InitTrainNet()
    @     0x7f553c9928d7  caffe::Solver<>::Init()
    @     0x7f553c992c7a  caffe::Solver<>::Solver()
    @     0x7f553c82db03  caffe::Creator_SGDSolver<>()
    @           0x40afb9  train()
    @           0x4077c8  main
    @     0x7f553a962830  __libc_start_main
    @           0x408099  _start
    @              (nil)  (unknown)

**Comment by adaxidedakaonang** [comment]
I have fixed the problem with upsample_param. Thanks anyway!

**Comment by DHW-Master** [comment]
我使用segnet训练自己的数据集,总共5类,但是训练时出现和你一样的问题,请问你是如何解决上面问题的,谢谢

**Comment by adaxidedakaonang** [comment]
我都忘了，好像是层数对不上吧
