### ISSUE TITLE
Weighted Softmax Loss

### ISSUE THREAD

**Issue by atanas1054** [alexgkendall/caffe-segnet#112]
Hello,

I want to use just the weighted softmax layer in SegNet without actually using the SegNet architecture.  How can I just take the weighted softmax layer and compile it on the latest caffe version?

**Comment by nathanin** [comment]
Try to copy the files src/caffe/layers/softmax_loss_layer.cpp and .cu and include/caffe/layers/softmax_loss_layer.hpp

Also check src/caffe/proto/caffe.proto and see if the LossParameter "class_weighting" is there.

Hope it works.

**Comment by atanas1054** [comment]
Hey,
There is no include/caffe/layers/softmax_loss_layer.hpp

**Comment by nathanin** [comment]
This repo is based on an old version of caffe. 

the repo here: https://github.com/TimoSaemann/caffe-segnet-cudnn5 has the layers factored out into individual header files. (see there's no "vision_layers.hpp", "loss_layers.hpp", etc.). I think this is how the most updated caffe does it still. 

https://github.com/TimoSaemann/caffe-segnet-cudnn5/blob/master/include/caffe/layers/softmax_loss_layer.hpp

**Comment by atanas1054** [comment]
It's working now. Thank you.
