### ISSUE TITLE
Trouble with training the SegNet

### ISSUE THREAD

**Issue by saviogeorge** [alexgkendall/caffe-segnet#114]
Hi Alex,

I tried to train the SegNet with a dataset obtained from the link:http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamSeq01/

However I face issues while training the SegNet(Please find the attached screenshot).

1) I understand for SegNet to work on my system we have to train it at first am I right? (Or the option is to make use of the online pretrained Segnet web demo). Here my intention is to make SegNet work on my system. 

2)I followed the SegNet tutorial to compile the caffe-Segnet specified in Link
:http://mi.eng.cam.ac.uk/projects/segnet/tutorial.html. Or have I missed something what is docker should i compile using docker?

Awaiting your reply!

Thank You!
Savio George

![screenshot at 2017-06-09 18_46_34](https://user-images.githubusercontent.com/20711873/27011712-0a04323e-4ec2-11e7-83ff-5a862e788d43.png)

**Comment by WeiyiLi** [comment]
It means your bottom[0]->height is 23 and bottom[1]->height() is 45. They are not equal so the check failed. Make sure the size of bottom[0] and bottom[1] are same in your upsample4 layer. I guess you need to trace back and check the size change after each layer, especially after each pooling layer. The stride value in each pooling layer will downsample your image to smaller size.

**Comment by saviogeorge** [comment]
Thanks a lot for your reply! Yes I will try debugging
