### ISSUE TITLE
ImportError: No module named google.protobuf.internal

### ISSUE THREAD

**Issue by saviogeorge** [alexgkendall/caffe-segnet#115]
I tried to to test the Segnet using the tutorial.
However i end up in this error even though i have installed the google.protobuf.

The environment variables required were also set in the .bashrc file and we also tried making changes to the makefile.config
![screenshot at 2017-06-19 13 52 55](https://user-images.githubusercontent.com/20711873/27282547-bb89f15e-54f0-11e7-8bcd-4966702a6f82.png)

**Comment by saviogeorge** [comment]
the protobuf version i use is 2.6.2 should i upgrade it 3 or later

**Comment by saviogeorge** [comment]
Issue solved

**Comment by BigMonkey1990** [comment]
how did you solve the problem, can you give us some detail?  Thank you!

**Comment by saviogeorge** [comment]
Yes Sure why not.
The reason was protobuf was not installed and 
Sudo pip install protobuf should fix the error.

However for me it was a little more complicated because I was not able to install the protobuf because of a different reason. The reason my system was making use of a proxy network and and my login password had special characters in it. The following links will give a better idea on this
https://github.com/pypa/pip/issues/3267
https://www.cyberciti.biz/faq/unix-linux-export-variable-http_proxy-with-special-characters/
https://www.cyberciti.biz/faq/linux-unix-bsd-appleosx-unicode-commandline-lookup/

So either you can encode your password using some commands such unum or else it is pretty straightforward change the password and avoid special characters.

well this resolved the problem and I was able to install the protobuf.
Note: For a better understanding please have a look at the attachment The error that you get when you try to install using pip command (When your password has some special characters
![pip error proxy issue](https://user-images.githubusercontent.com/20711873/27680177-3356d4fa-5cbb-11e7-8a2e-ff69aa876483.png)
)
