### ISSUE TITLE
The usage of upsample

### ISSUE THREAD

**Issue by 408550969** [alexgkendall/caffe-segnet#121]
There is such a paragraph in segnet_sun.prototxt:
layer {
name: "upsample5"
type: "Upsample"
bottom: "pool5"
bottom: "pool5_mask"
top: "pool5_D"
upsample_param {
scale: 2
upsample_h: 23
upsample_w: 30
}
}
Why there are 2 bottom?When I change to  one bottom,it will report an error:
Check failed: ExactNumBottomBlobs() == bottom.size() (2 vs. 1) Upsample Layer takes 2 bottom blob(s) as input.
Why must have 2 bottom? I just want to enlarge the source image.

**Comment by ZzzjzzZ** [comment]
int ExactNumBottomBlobs() const { return 2; } ; 
one for feature maps, and one for the max-pooling indeices;

**Comment by 408550969** [comment]
THANKS
