### ISSUE TITLE
Unclear licensing policy

### ISSUE THREAD

**Issue by ghost** [alexgkendall/caffe-segnet#14]
Hi.

https://github.com/alexgkendall/caffe-segnet/blob/segnet-cleaned/LICENSE
In LICENSE, there are 2 parts. The first one is about copyright and contains some "All rights reserved". The second part is about the license : CC BY 3.0 + a BSD-like license.

https://github.com/alexgkendall/caffe-segnet/blob/segnet-cleaned/README.md#license

> This extension to the Caffe library is released under a creative commons license which allows for personal and research use only. You can view a license summary here: http://creativecommons.org/licenses/by/3.0/deed.en_US

In README.md, we can read that the license "allows for personal and research use **only**". But then, CC BY 3.0 is quoted, and this license (like the BSD-like) does not forbid commercial, state, non profit foundations, etc use.

So the licensing policy is unclear for me. Is it free/libre as described by [the Free Software Foundation](https://www.gnu.org/philosophy/free-sw.html) and [Debian](https://www.debian.org/social_contract#guidelines)?

Regards.

**Comment by alexgkendall** [comment]
Hi @RyDroid sorry for the confusion I have just fixed the incorrect licence link. To clarify:

This software is released under a creative commons license which allows for personal and research use only. For a commercial license please contact the authors. You can view a license summary here: http://creativecommons.org/licenses/by-nc/4.0/
