### ISSUE TITLE
Is a 4GB GPU enough?

### ISSUE THREAD

**Issue by xmaster302** [alexgkendall/caffe-segnet#15]
Hi, @alexgkendall, could I train your SegNet on a 4GB GPU?

**Comment by alexgkendall** [comment]
Yes, that should be fine. Have a read of [SegNet Tutorial](http://mi.eng.cam.ac.uk/projects/segnet/tutorial.html)

"On a 12GB GPU such as a NVIDIA K40 or Titan X you should be able to use a batch size of 10 or 6 for SegNet-Basic or SegNet, respectively. If you have a smaller GPU then try and make this as large as will fit, however even a batch size of as low as 2 or 3 should still train well."

**Comment by salehiac** [comment]
Hi @alexgkendall , 

I'm using a 4GB GPU (an NVIDIA 970GTX) , but even with batch_size==1, I get an out of memory error:

I0511 17:17:43.059046  7342 solver.cpp:251] Learning Rate Policy: step
F0511 17:17:43.327872  7342 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

Could you please give me some pointers on how to make it work? thanks!

**Comment by heavenyc** [comment]
please try cudnn ,that solve this  problem
