### ISSUE TITLE
Benchmarking with caffe time

### ISSUE THREAD

**Issue by Crefeda** [alexgkendall/caffe-segnet#16]
Hi, 

I wanted to know if it is possible to benchmark layer by layer time for SegNet.

I tried ./build/tools/caffe time -model ../Models/segnet_basic_solver_small.prototxt -gpu 0 -iterations 1

but i get an error 
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 1:4: Message type "caffe.NetParameter" has no field named "net".

which according to the following post https://github.com/szagoruyko/loadcaffe/issues/5
is there any way to get it sorted? 
everything else works fine (training and testing) but I wanted to extract some performance metrics.

**Comment by alexgkendall** [comment]
Hi @Crefeda 

I think your problem might be that you are using the solver prototxt, ../Models/segnet_basic_solver_small.prototxt

You need to specify the model file, ie. segnet_train.prototxt

Other than that your command looks fine. Cheers.

**Comment by Crefeda** [comment]
Hi  alexgkendall,

thank you, you are right it .. had to take train.prototxt rather than the solver.prototxt file.
