### ISSUE TITLE
Use CamVid as lmdb format

### ISSUE THREAD

**Issue by johngmm** [alexgkendall/caffe-segnet#17]
Hi,

I have a problem when convert CamVid dataset to lmdb format (instead of using list of images like you did). I used the same model and only change the input layer to lmdb backend. The result when using lmdb format is always lower around 5% than using list of image. 

Any idea how to narrow down the problem?

Many thanks!

**Comment by nshaud** [comment]
I noted that when working with a list of images, Caffe normalizes the inputs in the [0, 1] range. However, it uses the exact values of the lmdb data (for RGB images, the [0,255] is usually used). You can either use *"scale: 1/256"* in the prototext file to scale it back to [0, 1] or use Python to normalize your data when building the lmdb.

I hope this can help you.

**Comment by alexgkendall** [comment]
Hi @johngmm , can you please check that both methods (lmdb vs. list) output the same data blob from their layer? As discussed it might be caused by some normalisation going on, scaling uint8 values from [0,255] to [0,1]?

You can access the output to a specific layer in python using something like this:

```
net.blobs['insert_data_layer_name'].data
```

Thanks,
Alex

**Comment by johngmm** [comment]
Thanks @alexgkendall !
I solved the problem, there is nothing wrong with segnet or scaling, I made a mistake when modify the caffe code and try to integrate it with segnet. Just use the full segnet code and it's fine!

**Comment by alexgkendall** [comment]
Glad to hear it!

**Comment by juntingzh** [comment]
@johngmm I am also trying to use lmdb as the input, but didn't make it. Could you please share the script to convert the image and groudtruth images in to lmdb format? Many thanks!
