### ISSUE TITLE
Testing some simple images 

### ISSUE THREAD

**Issue by ieted** [alexgkendall/caffe-segnet#18]
I was trying to predict the pixel labels of some simple RGB images (without ground truth annotations) using the pre-trained model (like webdemo does). I put my images in  '/home/ted/XMUdataset/KeLi' and generate a test.txt file in '/home/ted/XMUdataset' which looks like:

```
/home/ted/XMUdataset/KeLi/2001.jpg
/home/ted/XMUdataset/KeLi/2002.jpg
/home/ted/XMUdataset/KeLi/2003.jpg
/home/ted/XMUdataset/KeLi/2004.jpg
/home/ted/XMUdataset/KeLi/2005.jpg
/home/ted/XMUdataset/KeLi/2006.jpg
......
```

Then I changed the data layer in segnet_inference.prototxt like below:

```
layer {
  name: "data"
  type: "Data"
  top: "data"
  data_param {
    source: "/home/ted/XMUdataset/test.txt" # Change this to the absolute path to your data file
    batch_size: 1
  }
}
```

Finally, I edited the test_segmentation_camvid.py to this:

```
import numpy as np
import matplotlib.pyplot as plt
import os.path
import json
import scipy
import argparse
import math
import pylab
from sklearn.preprocessing import normalize
caffe_root = '/home/ted/SegNet/caffe-segnet/'           # Change this to the absolute directoy to SegNet Caffe
import sys
sys.path.insert(0, caffe_root + 'python')

import caffe

# Import arguments
parser = argparse.ArgumentParser()
parser.add_argument('--model', type=str, required=True)
parser.add_argument('--weights', type=str, required=True)
parser.add_argument('--iter', type=int, required=True)
args = parser.parse_args()

caffe.set_mode_gpu()

net = caffe.Net(args.model,
                args.weights,
                caffe.TEST)


for i in range(0, args.iter):

    net.forward()

    image = net.blobs['data'].data
    predicted = net.blobs['prob'].data
    image = np.squeeze(image[0,:,:,:])
    output = np.squeeze(predicted[0,:,:,:])
    ind = np.argmax(output, axis=0)

    r = ind.copy()
    g = ind.copy()
    b = ind.copy()

    Sky = [128,128,128]
    Building = [128,0,0]
    Pole = [192,192,128]
    Road_marking = [255,69,0]
    Road = [128,64,128]
    Pavement = [60,40,222]
    Tree = [128,128,0]
    SignSymbol = [192,128,128]
    Fence = [64,64,128]
    Car = [64,0,128]
    Pedestrian = [64,64,0]
    Bicyclist = [0,128,192]
    Unlabelled = [0,0,0]

    label_colours = np.array([Sky, Building, Pole, Road, Pavement, Tree, SignSymbol, Fence, Car, Pedestrian, Bicyclist, Unlabelled])
    for l in range(0,11):
        r[ind==l] = label_colours[l,0]
        g[ind==l] = label_colours[l,1]
        b[ind==l] = label_colours[l,2]

    rgb = np.zeros((ind.shape[0], ind.shape[1], 3))
    rgb[:,:,0] = r/255.0
    rgb[:,:,1] = g/255.0
    rgb[:,:,2] = b/255.0

    image = image/255.0

    image = np.transpose(image, (1,2,0))
    output = np.transpose(output, (1,2,0))
    image = image[:,:,(2,1,0)]


    #scipy.misc.toimage(rgb, cmin=0.0, cmax=255).save(IMAGE_FILE+'_segnet.png')

    plt.figure()
    plt.imshow(image,vmin=0, vmax=1)
    plt.figure()
    plt.imshow(rgb,vmin=0, vmax=1)
    plt.show()


print 'Success!'
```

Yet after I run the script above, I got the following error:

```
I0114 15:04:08.348337 34065 layer_factory.hpp:74] Creating layer data
I0114 15:04:08.348378 34065 net.cpp:90] Creating Layer data
I0114 15:04:08.348390 34065 net.cpp:368] data -> data
I0114 15:04:08.348405 34065 net.cpp:120] Setting up data
F0114 15:04:08.348466 34065 db.cpp:18] Check failed: status.ok() Failed to open leveldb /home/ted/XMUdataset/test.txt
IO error: /home/ted/XMUdataset/test.txt/LOCK: Not a directory
*** Check failure stack trace: ***
Aborted (core dumped)
```

Could anyone give me a hint about where I am wrong? So many thanks in advance.

**Comment by alexgkendall** [comment]
You should still use the DenseImageData layer, so replace the  data layer in segnet_inference.prototxt as follows:

```
layer {
  name: "data"
  type: "DenseImageData"
  top: "data"
  top: "label"
  dense_image_data_param {
    source: "/home/ted/XMUdataset/test.txt"
    batch_size: 1
  }
}
```

You will also need a 'dummy' image file for the label image, so for example you could modify your test.txt to be:

```
/home/ted/XMUdataset/KeLi/2001.jpg /home/ted/XMUdataset/KeLi/2001.jpg
/home/ted/XMUdataset/KeLi/2002.jpg /home/ted/XMUdataset/KeLi/2001.jpg
/home/ted/XMUdataset/KeLi/2003.jpg /home/ted/XMUdataset/KeLi/2001.jpg
/home/ted/XMUdataset/KeLi/2004.jpg /home/ted/XMUdataset/KeLi/2001.jpg
/home/ted/XMUdataset/KeLi/2005.jpg /home/ted/XMUdataset/KeLi/2001.jpg
/home/ted/XMUdataset/KeLi/2006.jpg /home/ted/XMUdataset/KeLi/2001.jpg
......
```

**Comment by ieted** [comment]
@alexgkendall Thanks for your attention. I followed your instruction but still I got the following error:

```
F0115 16:34:42.940047  7304 upsample_layer.cpp:63] Check failed: bottom[0]->height() == bottom[1]->height() (23 vs. 41) 
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by alexgkendall** [comment]
What dimension are your input images? If they are not 480x360 like the CamVid examples then you must modify the upsample layers in the model prototxt definition. When padding is required you must specify upsample_w and upsample_h

**Comment by ieted** [comment]
@alexgkendall I fixed the problem you mentioned and now everything functions well. Thank you so much.

**Comment by nathanin** [comment]
Sorry to raise a closed issue from the grave, but I have an additional question about inserting my own data by way of the python interface.

I wish to load an image as a numpy array in python, and perform the segmentation with a trained model. i.e. not have individual tiles stored on disk beforehand, but to sample from a very large image on the fly. 
I'm successful when I save the tiles to disk and use a list.txt, as suggested above. 

I've tried the following:

```
img_data = cv2.imread(img_path)
img_data = np.transpose(img_data, (2,0,1)) # (256,256,3)->(3,256,256)
img_data = img_data[(2,1,0), :, :] #  RGB->BGR
net.blob['data'].data[0,:,:,:] = img_data

out = net.forward()
```
And while the program executes, the input is clearly not `img_data`. I know because my inference prototxt data layer is such: 
```
layer {
  name: "data"
  type: "DenseImageData"
  top: "data"
  top: "label"
  dense_image_data_param {
    source: "dummy_list.txt"
    batch_size: 1
  }
}
```
and dummy_list.txt is a single line:
```
rgb_image.jpg black_and_white.png
```

All of the outputs I get are of my trained model working on `rgb_image.jpg`, although I would think that my code would replace the `'data'` layer with new image data. It appears to disregard this modification of the `data` layer. 

The alternative:
```
out=net.forward_all(data=image_data)
```
produces the following:
```
Traceback (most recent call last):
  File "./test_tiles_pullimgs.py", line 163, in <module>
    run(model, weights, tiledir, writeto)
  File "./test_tiles_pullimgs.py", line 99, in run
    out = net.forward_all(data=A)
  File "/home/nathan/caffe-segnet/python/caffe/pycaffe.py", line 168, in _Net_forward_all
    outs = self.forward(blobs=blobs, **batch)
  File "/home/nathan/caffe-segnet/python/caffe/pycaffe.py", line 87, in _Net_forward
    raise Exception('Input blob arguments do not match net inputs.')
Exception: Input blob arguments do not match net inputs.
```

For the time being, I can work by pre-cutting, saving, and generating a list.txt.

Still, if there is a way to have the network accept input data from python, as in normal caffe, please show me where I have gone wrong. Thanks!

**Comment by nk-dev0** [comment]
I'd also like to have some light shed on @nathanin's issue. I have a huge 6000x6000 image that I'd like to segment. I'd like to use a sliding window approach by chipping out each 512x512 tile (size which I trained my network with), segment, and then compile all 512x512 tiles back into the original 6000x6000 size. 

It would be very expensive to have to chip out the image into individual jpg's, place names into a test.txt file, and then re-compile all tiles back into the original, so I'd like to try to accomplish this all in internal memory without so much I/O. Thanks.

**Comment by Arsey** [comment]
@nathanin , @nkrall have you solved the issue with manual setting of the `net.blob['data'].data`?

I have a trick for it:
1. create the source file with one example
2. put image content into the file that is set in the source file
3. init model
4. do forward

the only big issue that I can't solve with the trick, is that it doesn't work well if you want to initialize model once and then do only forward multiple times with different images with the same path (image's content changes and the path is constant). The fork somehow always outputs results from the previous image.
