### ISSUE TITLE
About example/net.prototxt

### ISSUE THREAD

**Issue by tracer9** [alexgkendall/caffe-segnet#19]
Hi @alexgkendall ! Recently I am reading your segnet framework and I found something strange!

In the caffe_segnet/examples/segnet/net.prototxt, I found that the layer conv1's bottom blob is said to be norm, however, there is no norm blob! I also refer your SegNet-Tutorial. In the Models/segnet_basic_train.prototxt, there is a layer called norm which connect the blobs data and norm.

So is there something wrong or should we correct it ?

**Comment by alexgkendall** [comment]
Hi @tracer9 ,

The model in caffe_segnet/examples/segnet/net.prototxt was an old design. I've removed it to reduce any confusion. You should use the models in SegNet-Tutorial. As you point out, the segnet_basic model has a normalisation layer (might not be necessary but it helps with smaller datasets/models).

Cheers.
