### ISSUE TITLE
error in 'make runtest'

### ISSUE THREAD

**Issue by amiltonwong** [alexgkendall/caffe-segnet#2]
Dear all,

I had followed the general installation steps for installing caffe-segnet. But I came across the following error in 'make runtest' step. 

[----------] Global test environment tear-down
[==========] 1400 tests from 222 test cases ran. (190603 ms total)
[  PASSED  ] 1399 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] NetUpgradeTest.TestUpgradeV1LayerType

 1 FAILED TEST
  YOU HAVE 2 DISABLED TESTS

Could someone suggest me how to fix it?

Best regards,
Milton

**Comment by kezbreen** [comment]
Hi @amiltonwong 

This is a minor bug in our caffe.proto. I'll have the fix up shortly. 

In the mean time this won't affect your usage of caffe-segnet (the bug concerns an older deprecated specification format).

Cheers,
Kesar

**Comment by kezbreen** [comment]
Fix is up.
