### ISSUE TITLE
make runtest error - What is my "Compute Capability" ?

### ISSUE THREAD

**Issue by odedyec** [alexgkendall/caffe-segnet#22]
While trying to run `make runtest`, I receive the infamous error

> F0216 12:58:41.889211 12098 cudnn_softmax_layer.cpp:19] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
> **\* Check failure stack trace: ***
>     @     0x2b111b85adaa  (unknown)
>     @     0x2b111b85ace4  (unknown)
>     @     0x2b111b85a6e6  (unknown)
>     @     0x2b111b85d687  (unknown)
>     @     0x2b111d2122e5  caffe::CuDNNSoftmaxLayer<>::LayerSetUp()
>     @     0x2b111d23221d  caffe::SoftmaxWithLossLayer<>::LayerSetUp()
>     @     0x2b111d29184b  caffe::Net<>::Init()
>     @     0x2b111d293592  caffe::Net<>::Net()
>     @           0x6ff069  caffe::NetTest<>::InitNetFromProtoString()
>     @           0x6bfd9c  caffe::NetTest<>::InitTinyNet()
>     @           0x6f3dc1  caffe::NetTest_TestBottomNeedBackward_Test<>::TestBody()
>     @           0x7bf963  testing::internal::HandleExceptionsInMethodIfSupported<>()
>     @           0x7b65a7  testing::Test::Run()
>     @           0x7b664e  testing::TestInfo::Run()
>     @           0x7b6755  testing::TestCase::Run()
>     @           0x7b9a98  testing::internal::UnitTestImpl::RunAllTests()
>     @           0x7b9d27  testing::UnitTest::Run()
>     @           0x451d4a  main
>     @     0x2b111de7aec5  (unknown)
>     @           0x457e99  (unknown)
>     @              (nil)  (unknown)
> make: **\* [runtest] Aborted (core dumped)

I found a few conversations and all of them state that cudnn will not work if the compute capability of my GPU is smaller than 3.0. 
I have a [NVidia Quadro 2000](http://www.nvidia.com/object/product-quadro-2000-us.html). How do I know what is my compute capability? Couldn't find it

Can something else cause this issue? 
BTW, I'm working on a fresh Ubuntu 14.04, and Cuda6.5 required for SegNet. On CPU everything works (but very slowly).

**Comment by alexgkendall** [comment]
Can you run normal Caffe? If not, then perhaps it is best to consult the Caffe documentation and get that working first?

If you still cannot get it to work then try compiling without cudnn, it will still be reasonably fast on a GPU.
