### ISSUE TITLE
Model trained on additional public 3.5K dataset

### ISSUE THREAD

**Issue by coldmanck** [alexgkendall/caffe-segnet#25]
Thanks for sharing this fantastic structure and code of SegNet. According to your tutorial, I already managed to reproduce your first two result (SegNet-basic and SegNet). However, I would like to see better performance of SegNet (which trained on additional public 3.5K dataset). Could you please share your trained model (.caffemodel file)? Or kindly share the entire 3.5K dataset (with annotation) so that I can train by myself. 

Thanks,
Meng-Jiun Chiou

**Comment by alexgkendall** [comment]
Hey - I'm afraid you'll have to collate this dataset yourself. Details are in the paper. 

You might be interested in the driving webdemo for better performance:
https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Example_Models/segnet_model_zoo.md

**Comment by eugenelawrence** [comment]
Hey @coldmanck ,have you reproduced the result of Bayesian Segnet?
I cann't reproduced the three measures(global acc., class avg. and mean iou) on the paper.
Can you give me a hand?
