### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by mrgloom** [alexgkendall/caffe-segnet#26]
For example my images have only 2 class {0,1} labels, assume 0 class is background and 1 class in some object.
Is it will be helpfull if I use some images with only background or it will be harmfull, because of too unbalanced data?

**Comment by jorgyz** [comment]
In my experimenting including images with only background seems to help reduce the false-positives, especially if your background has a lot of variability.  You can balance adjust the class weighting for the loss function to handle the class imbalance.
