### ISSUE TITLE
Merging with current caffe build

### ISSUE THREAD

**Issue by rshanor** [alexgkendall/caffe-segnet#29]
Hey @alexgkendall do you have any advice on merging the segnet version of caffe with the current BVLC caffe build? I am trying to use some of their new features. Thanks!

**Comment by nshaud** [comment]
Seconded, this could be very useful for new SegNet users.

Especially, using Caffe's batch normalization layer gives nearly the same results and avoid having to use the "compute_statistics.py" script.

**Comment by alexgkendall** [comment]
Hey , I agree. Unfortunately I haven't been able to find the time so no plans as yet.

**Comment by jimchenhub** [comment]
I implement some layers in `SegNet` on current version of caffe. You can use it the same way as caffe-segnet tutorial said but without BN layers. 

My repository: https://github.com/jimchenhub/new-caffe-segnet 
Please feel free to give suggestion to it.
@rshanor @nshaud
