### ISSUE TITLE
compute_bn_statistics Process finished with exit code 139

### ISSUE THREAD

**Issue by cslxiao** [alexgkendall/caffe-segnet#32]
I use LMDB data to train a model successfully. But when I run the modified compute_bn_statistics.py, it crashes after processing a few images (randomly from 1 to 15).

_progress: 1/100
progress: 2/100
progress: 3/100
progress: 4/100
progress: 5/100
progress: 6/100
progress: 7/100

Process finished with exit code 139_  
(7 is random sometimes 1, the largest 13 in several tirals)

Why it happens? It goes the same for cpu and gpu. How to fix it?
May it be out-of-memory?

**Comment by alexgkendall** [comment]
Try and remove the Accuracy and Loss layers from the prototxt. They are not needed to compute BN statistics. I see this sometime too and this solves the problem for me - but I'm not sure of the cause.

Cheers.

**Comment by cslxiao** [comment]
Fantastic, I followed your advice and solved the problem. Thanks @alexgkendall .
