### ISSUE TITLE
USE_CUDNN errors

### ISSUE THREAD

**Issue by ButlerRobotics** [alexgkendall/caffe-segnet#36]
_Ubuntu 14.04
CUDA 7.5
cuDNN 4_

I am getting multiple errors when I uncomment **USE_CUDNN := 1** in the Makefile.config.

I can not reproduce the same errors when using vanilla caffe with similar Makefile.config.

Here is an example of the errors I am getting (1 of 20):

`src/caffe/layers/cudnn_conv_layer.cu(81): error: argument of type "cudnnAddMode_t" is incompatible with parameter of type "const void *" 
          detected during instantiation of "void caffe::CuDNNConvolutionLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &, const std::vector<caffe::Blob<Dtype> *, std::allocator<caffe::Blob<Dtype> *>> &) [with Dtype=float]" 
(157): here
`

All errors relate to the file located here: src/caffe/layers/cudnn_conv_layer.cu
Is this an issue with cuDNN v4?

I can post all errors if required.

**Comment by alexgkendall** [comment]
This version only supports cudnn v2!

**Comment by stevefoy** [comment]
I'm looking at a similar issue with cuDNN v4 too, do you think there is much work getting it to work with cuDNN v4.

**Comment by ButlerRobotics** [comment]
Ok, good to know.

Is it possible to leave this open as a feature request? I just noticed that the same issue was posted twice under closed issues.

**Comment by stevefoy** [comment]
just an update : I merged segnet with a more recent version of caffe..... ok so far, one test segnet basic was taking 250ms for frame with cudnn 3.0 and now newer caffe and cudnn 4.0 ~150ms.
fork here, maybe it helps someone, but be aware needs more work:
https://github.com/stevefoy/caffe#caffe
Preliminary Tested on :
TX1
Ubuntu 14.04
CUDA 7.0
cuDNN 4

**Comment by alexgkendall** [comment]
FYI I've added a note to the `README.md`:

This version supports cudnn v2 acceleration. @TimoSaemann has a branch supporting a more recent version of Caffe (Dec 2016) with cudnn v5.1: https://github.com/TimoSaemann/caffe-segnet-cudnn5

**Comment by stevefoy** [comment]
Great news alexgkendall, thanks
