### ISSUE TITLE
Accuracy layer uncertain per-class behavior

### ISSUE THREAD

**Issue by arassadin** [alexgkendall/caffe-segnet#38]
Accuracy layer don't handles the case when class is missed in GT sample. It results to _NaN_ value for per-class accuracy value for this particular class since that total number of class presence in sample (mini-batch) is 0 (then - division by zero):
`top[1]->mutable_cpu_data()[i] = accuracies[i] / nums[i];`

Caffe already fixed it.

**Comment by arassadin** [comment]
No additional tests needed, I suppose

**Comment by alexgkendall** [comment]
Thanks!
