### ISSUE TITLE
HowTo obtain segmentation output (pixel-wise labeling)

### ISSUE THREAD

**Issue by amiltonwong** [alexgkendall/caffe-segnet#4]
Hi, Alex,

After I train the model on dataset Camvid, and perform testing (label prediction) on a new image using the following command.

./caffe test -model examples/segnet/net.prototxt -weights examples/segnet/traintest_iter_200.caffemodel -gpu 0 -iterations 1

I could get the loss and accuracy output (details here: https://goo.gl/KIa5Vb ), so segmentation output (pixel-wise labeling prediction) for the test image must be computed in someplace. 
My question is :
Where could I obtain that segmentation output (pixel-wise labeling)? Or which steps have to be appended?

Thanks in advance!

Milton

**Comment by jorgyz** [comment]
@amiltonwong I have the same question. Were you able to figure out how to get the pixel-wise output labels?

**Comment by amiltonwong** [comment]
@jorgyz ,I think the most probable file will be https://github.com/alexgkendall/caffe-segnet/tree/segnet-cleaned/examples/segnet/net.prototxt, but I couldn't figure out the pixel-wise labeling in it.
Any ideas or comment?

**Comment by alexgkendall** [comment]
Hi @amiltonwong and @jorgyz, sorry for the late reply!

Thank you for your interest in SegNet. I'm just in the process of putting together a tutorial for training and testing the system. I'll let you know when it is available (hopefully in the next few days) but it will include all my test scripts to solve this exact problem.

Thanks,
Alex

**Comment by amiltonwong** [comment]
Great, @alexgkendall. 
I can't wait to see it :)

**Comment by alexgkendall** [comment]
Hi @amiltonwong  @jorgyz and others, here is a tutorial which should guide you through all the steps to train and generate a segmentation output with SegNet!
http://mi.eng.cam.ac.uk/projects/segnet/tutorial.html
