### ISSUE TITLE
make runtest fails

### ISSUE THREAD

**Issue by albertxavier001** [alexgkendall/caffe-segnet#42]
`make all` and `make test` are OK when compiling caffe-segnet.
When `make runtest`, error occurs:

[ RUN      ] DenseImageDataLayerTest/1.TestRead
F0530 23:05:28.438096  8335 data_transformer.cpp:230] Check failed: height <= img_height (360 vs. 0) 
**\* Check failure stack trace: ***
    @     0x7f590b9e0d7d  google::LogMessage::Fail()
    @     0x7f590b9e2c1d  google::LogMessage::SendToLog()
    @     0x7f590b9e0998  google::LogMessage::Flush()
    @     0x7f590b9e347e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5909bf01fb  caffe::DataTransformer<>::Transform()
    @     0x7f5909ccb7dc  caffe::DenseImageDataLayer<>::InternalThreadEntry()
    @     0x7f5901e7909a  (unknown)
    @     0x7f59093776aa  start_thread
    @     0x7f59090aceed  (unknown)
Makefile:468: recipe for target 'runtest' failed
make: **\* [runtest] Aborted (core dumped)

Error also occurs when trainging:

I0530 23:10:23.171794  8530 net.cpp:90] Creating Layer conv3_2
I0530 23:10:23.171803  8530 net.cpp:410] conv3_2 <- conv3_1
I0530 23:10:23.171813  8530 net.cpp:368] conv3_2 -> conv3_2
I0530 23:10:23.171825  8530 net.cpp:120] Setting up conv3_2
    @     0x7f7d2e4b28eb  caffe::DataTransformer<>::Transform()
    @     0x7f7d2e58a9bc  caffe::DenseImageDataLayer<>::InternalThreadEntry()
    @     0x7f7d2633a09a  (unknown)
    @     0x7f7d250766aa  start_thread
    @     0x7f7d2d732eed  (unknown)
Aborted (core dumped)

Thank you for your help!

**Comment by alexgkendall** [comment]
Hey, I've just pushed a new data augmentation feature to the code base. I think I've removed all the bugs now - can you please do a `git pull` and see if the tests now run without any errors?

Cheers!

**Comment by albertxavier001** [comment]
Hi, @alexgkendall , Thanks for quick response.
There is no error when I use atlas for blas, but when I use openblas, an another error occurs:
[ RUN      ] PowerLayerTest/1.TestPowerTwoGradient
**\* Aborted at 1464659604 (unix time) try "date -d @1464659604" if you are using GNU date ***
PC: @     0x7fba38f9bcf7 daxpy_kernel_8
**\* SIGILL (@0x7fba38f9bcf7) received by PID 24756 (TID 0x7fba3eae09c0) from PID 955890935; stack trace: ***
    @     0x7fba385a7d10 (unknown)
    @     0x7fba38f9bcf7 daxpy_kernel_8
    @     0x7fba38f9beef daxpy_k
    @     0x7fba38f8087d cblas_daxpy
    @     0x7fba38ef2a68 caffe::PowerLayer<>::Backward_cpu()
    @           0x45b42d caffe::Layer<>::Backward()
    @           0x45cc3c caffe::GradientChecker<>::CheckGradientSingle()
    @           0x46847c caffe::GradientChecker<>::CheckGradientEltwise()
    @           0x7414e6 caffe::PowerLayerTest<>::TestBackward()
    @           0x7dfdaa testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7d5169 testing::Test::Run()
    @           0x7d5247 testing::TestInfo::Run()
    @           0x7d5385 testing::TestCase::Run()
    @           0x7d55fd testing::internal::UnitTestImpl::RunAllTests()
    @           0x7df92a testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x7d49c1 testing::UnitTest::Run()
    @           0x451272 main
    @     0x7fba381eda40 (unknown)
    @           0x457039 _start
Makefile:468: recipe for target 'runtest' failed
make: **\* [runtest] Illegal instruction (core dumped)

**Comment by albertxavier001** [comment]
I think the problem above is openblas problem. Forget it.
