### ISSUE TITLE
Missing folder build/tools/caffe

### ISSUE THREAD

**Issue by Timo-hab** [alexgkendall/caffe-segnet#46]
Hallo, 

when I follow the tutorial it says:

./SegNet/caffe-segnet/build/tools/caffe train -gpu 0 -solver /SegNet/Models/segnet_solver.prototxt  # This will begin training SegNet on GPU 0

However, this path does not exist for me. There is no build/tools/caffe. 
In caffe-segnet are 3 caffe folders. In caffe-segnet/src/caffe, caffe-segnet/python/caffe and caffe-segnet/include/caffe. However, it does not work with any of these paths. 

Can someone help?

**Comment by alexgkendall** [comment]
You need to compile it - see the caffe installation instructions for details.

**Comment by ansj11** [comment]
Hi,
I alse have this problem but i have compile the caffe and have build/tools/caffe, but it is red and not find this command
