### ISSUE TITLE
Data Question

### ISSUE THREAD

**Issue by ghost** [alexgkendall/caffe-segnet#6]
Hi there, 

When I run SegNet on my own data, I produce the following error: 

---

I1016 18:40:51.863139 20505 net.cpp:120] Setting up upsample3
F1016 18:40:51.863159 20505 upsample_layer.cpp:63] Check failed: bottom[0]->height() == bottom[1]->height() (45 vs. 32) 
**\* Check failure stack trace: ***
    @     0x7faf9a4d8ddd  (unknown)
    @     0x7faf9a4dacc0  (unknown)
    @     0x7faf9a4d89ac  (unknown)
    @     0x7faf9a4db6be  (unknown)
    @     0x7faf9fca971e  caffe::UpsampleLayer<>::Reshape()
    @     0x7faf9fce8512  caffe::Net<>::Init()
    @     0x7faf9fceaa35  caffe::Net<>::Net()
    @     0x7faf9fcf60d6  caffe::Solver<>::InitTrainNet()
    @     0x7faf9fcf73c0  caffe::Solver<>::Init()
    @     0x7faf9fcf7586  caffe::Solver<>::Solver()
    @           0x40fd00  caffe::GetSolver<>()
    @           0x408050  train()
    @           0x405b79  main
    @     0x7faf92392700  __libc_start_main
    @           0x4061b9  _start
Aborted (core dumped)

---

The runtest is all good. And so is the example training. I'm trying to figure out the problem with my data. I'm very new to caffe so a little help would really be appreciated!

**Comment by alexgkendall** [comment]
Hi, sorry for the late reply!

The problem here is that your network is upsampling the feature map to dimensions that are not consistent with your encoder. Therefore when the max pooling indices are used to upsample the dimensions do not match. You need to ensure that the input dimensions of both the feature map and pooled indices are the same when you feed them into an upsample layer.

If you show me your model file perhaps I can help further? Hope this helps!

Cheers,
Alex

**Comment by alexgkendall** [comment]
Hi @brewiss  If you haven't been able to resolve your problem, maybe this tutorial may help?
http://mi.eng.cam.ac.uk/projects/segnet/tutorial.html

Thanks,
Alex

**Comment by trminh89** [comment]
Hi @alexgkendall ,

I got the same problem. My data have 8 classes. Can you please have a look at my  segnet_basic_train.prototxt file (http://pastebin.com/8SFwqtij) and show me what's wrong?

Thanks!

F1125 15:28:05.204437  5212 upsample_layer.cpp:63] Check failed: bottom[0]->height() == bottom[1]->height() (59 vs. 60) 
**\* Check failure stack trace: ***
    @     0x7f7bf11c3daa  (unknown)
    @     0x7f7bf11c3ce4  (unknown)
    @     0x7f7bf11c36e6  (unknown)
    @     0x7f7bf11c6687  (unknown)
    @     0x7f7bf1557af9  caffe::UpsampleLayer<>::Reshape()
    @     0x7f7bf15f3f07  caffe::Net<>::Init()
    @     0x7f7bf15f5cb2  caffe::Net<>::Net()
    @     0x7f7bf14ecb00  caffe::Solver<>::InitTrainNet()
    @     0x7f7bf14edbe3  caffe::Solver<>::Init()
    @     0x7f7bf14eddb6  caffe::Solver<>::Solver()
    @           0x40edf0  caffe::GetSolver<>()
    @           0x408683  train()
    @           0x406c81  main
    @     0x7f7bf06d5ec5  (unknown)
    @           0x40722d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
