### ISSUE TITLE
Hｏｗ　ｔｏ　ｇｅｔ　３９　ｃｌａｓｓｅｓ　ｗｅｉｇｈｔｓ　ｏｆ　SUN　ｄａｔａｓｅｔ　ｉｎ　ｓｅｇｎｅｔ＿ｔｒａｉｎ．ｐｒｏｔｏｔｘｔ？

### ISSUE THREAD

**Issue by clovercoser** [alexgkendall/caffe-segnet#70]
Hｉ，　I　ａｍ　ｔｒａｉｎｉｎｇ　ｓｅｇｎｅｔ　ｏｎ　SUN＿RGBD　ｄａｔａｓｅｔ　ｗｈｉｃｈ　ｈａｓ　３９　ｃｌａｓｓｅｓ．　Hｏｗ　ｃａｎ　I　ｇｅｔ　ｔｈｅ　３９　ｃｌａｓｓｅｓ　ｗｅｉｇｈｔｓ　ｖａｌｕｅ　ｏｆ　SUN　ｄａｔａｓｅｔ　ｉｎ　ｓｅｇｎｅｔ＿ｔｒａｉｎ．ｐｒｏｔｏｔｘｔ？　Cａｎ　I　ｃａｃｌｕａｔｅ　ｔｈｅ　ｒａｔｉｏ　ｏｆ　ｅａｃｈ　ｃｌａｓｓｅｓ　ｂｙ　ｃｏｕｎｔｉｎｇ　ｖａｌｕｅ　ｏｆ　ｅｖｅｒｙ　ｐｉｘｅｌ　ｉｎ　ａｌｌ　ｔｒａｉｎｉｎｇ　ｌａｂｅｌ　ｉｍａｇｅｓ，　ａｎｄ　ｔａｋｅ　ｔｈｅ　ｒａｔｉｏ　ａｓ　ｗｅｉｇｈｔｓ？　Bｕｔ　ｉｔ　ｓｅｅｍｓ　ｔｈｅ　ｗｅｉｇｈｔｓ　ｉｎ　ｔｈｅ　ｅｘａｍｐｌｅ　ｐｒｏｔｏｔｘｔ　ａｒｅ　ｎｏｔ　ｒａｔｉｏｓ，　ｓｏｍｅ　ｇｒｅａｔｅｒ　ｔｈａｎ　１．　Lｏｏｋｉｎｇ　ｆｏｒｗａｒｄ　ｔｏ　ｙｏｕｒ　ｒｅｐｌｙ．

**Comment by ArunJ1** [comment]
i am stuck with same issue??any reply
