### ISSUE TITLE
Cuda 8 make runtest error

### ISSUE THREAD

**Issue by Timo-hab** [alexgkendall/caffe-segnet#73]
Could anyone successfully compile caffe-segnet by using Cuda 8, cudnn v3 ?

I did:
mkdir build
cd build
cmake ..
make -j4 all
make install
make runtest

But make runtest gives me 5 failed testes:

[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionGroupCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientGroupCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSobelConvolutionCuDNN, where TypeParam = float

**Comment by Timo-hab** [comment]
By using cudnn v2, i get only 4 failed tests:

[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientGroupCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionCuDNN, where TypeParam = float
[  FAILED  ] CuDNNConvolutionLayerTest/0.TestSimpleConvolutionGroupCuDNN, where TypeParam = float

**Comment by Timo-hab** [comment]
When i compile it using the standard compilation (make all, make test, make runtest), i get the same error for "make runtest".

**Comment by alexgkendall** [comment]
FYI I've added a note to the `README.md`:

This version supports cudnn v2 acceleration. @TimoSaemann has a branch supporting a more recent version of Caffe (Dec 2016) with cudnn v5.1: https://github.com/TimoSaemann/caffe-segnet-cudnn5

**Comment by dennishnf** [comment]
The same problem using Cuda 9, cudnn v4
