### ISSUE TITLE
Dense Image Data Layer Accepted Data Types

### ISSUE THREAD

**Issue by isn4** [alexgkendall/caffe-segnet#77]
Hi, I'm trying to run my own data through SegNet and have run into an issue.
My image data is in greyscale binary format (ie, not .jpg, .png, etc).
The only changes I've made to the example have to do with which data it points to and thus, my train.prototxt file looks like:

name: "VGG_ILSVRC_16_layer"
layer {
  name: "data"
  type: "DenseImageData"
  top: "data"
  top: "label"
  dense_image_data_param {
    source: "/home/caffe-segnet/tutorial/CamVid/zf_train.txt"   # Change this to the absolute path to your data file
    batch_size: 4               # Change this number to a batch size that will fit on your GPU
    shuffle: true
  }
}

And my train.txt file looks like:

/home/z-inputs/flip0/z0002 /home/z-outputs/flip0/z0002
/home/z-inputs/flip0/z0004 /home/z-outputs/flip0/z0004
/home/z-inputs/flip0/z0006 /home/z-outputs/flip0/z0006
/home/z-inputs/flip0/z0008 /home/z-outputs/flip0/z0008
/home/z-inputs/flip0/z0010 /home/z-outputs/flip0/z0010
..........

However, when I attempt to train Segnet with my data I get this error:

I0921 17:11:24.491659 11960 layer_factory.hpp:74] Creating layer data
I0921 17:11:24.491912 11960 net.cpp:90] Creating Layer data
I0921 17:11:24.492297 11960 net.cpp:368] data -> data
I0921 17:11:24.492712 11960 net.cpp:368] data -> label
I0921 17:11:24.492748 11960 net.cpp:120] Setting up data
I0921 17:11:24.492784 11960 dense_image_data_layer.cpp:41] Opening file /home/caffe-segnet/tutorial/CamVid/zf_train.txt
I0921 17:11:24.533395 11960 dense_image_data_layer.cpp:51] Shuffling data
I0921 17:11:24.534602 11960 dense_image_data_layer.cpp:56] A total of 370 exampl
es.
E0921 17:11:24.632740 11960 io.cpp:78] Could not open or find file /home/z-inputs/flip0/z0732
E0921 17:11:24.773319 11960 io.cpp:78] Could not open or find file /home/z-outputs/flip0/z0732
**\* Aborted at 1474492284 (unix time) try "date -d @1474492284" if you are using
 GNU date ***
PC: @     0x7fa3d5a10a31 caffe::Blob<>::Reshape()
**\* SIGFPE (@0x7fa3d5a10a31) received by PID 11960 (TID 0x7fa3d61b89c0) from PID
 18446744072998685233; stack trace: ***

I would really appreciate if someone could give me some insight. Does the DenseImageData layer type not accept binary data? Does my data have to be in .png format? And if so, can I substitute the DenseImageData layer with a normal Data layer?

Thanks!

**Comment by chuxindi0325** [comment]
I have the same problem with you.Have you solved it?

**Comment by isn4** [comment]
Hi @chuxindi0325 - apologies for the delayed response.
I ended up converting my binary data into .png files so that it was in the same format as the original SegNet data
