### ISSUE TITLE
How to create annotated image for Segnet?

### ISSUE THREAD

**Issue by monjoybme** [alexgkendall/caffe-segnet#86]
I checked Camvid image dataset. I am trying to create annotated image just like Camvid annotated image but failed. Please suggest any tool or algorithm for the same. Please suggest can I use binary image as ground truth?

**Comment by TimoSaemann** [comment]
You could use the JS Segment Annotator to label images.  
https://github.com/kyamagu/js-segment-annotator

**Comment by monjoybme** [comment]
thank you I tried this tool  but in my data set this tool creating lots of problem. Is there any other tool ?

**Comment by TimoSaemann** [comment]
LabelMe is a common tool for that as well.

**Comment by ArunJ1** [comment]
I tried with LabelMe....But I am not able to download the images after annotation...I am able to download only XML file.....Can you pls help me??

**Comment by ArunJ1** [comment]
> LabelMe is a common tool for that as well.

I tried with LabelMe....But I am not able to download the images after annotation...I am able to download only XML file.....Can you pls help me??

**Comment by monjoybme** [comment]
Write a code to get labeled data from the XML files.


Thanks and Regards,
Monjoy Saha


The information contained in this electronic message and any attachments to
this message are intended for the exclusive use of the addressee(s) and may
contain proprietary, confidential or privileged information. If you are not
the intended recipient, you should not disseminate, distribute or copy this
e-mail. Please notify the sender immediately and destroy all copies of this
message and any attachments.

**Comment by monjoybme** [comment]
closed

**Comment by monjoybme** [comment]
The issue has been solved.
