### ISSUE TITLE
Unknown blob input norm to layer 0 - can't find prototxt & dataset

### ISSUE THREAD

**Issue by etienne87** [alexgkendall/caffe-segnet#9]
Hello,

I can't find the proper net.prototxt, i'm trying to use the one in /examples but it seems to use an undefined layer called "norm".

Also in the tutorial the link to CamVid datase seems to be broken (I'm trying with http://mi.eng.cam.ac.uk/research/projects/VideoRec/ but there is much less frames (101 instead of 700)

**Comment by alexgkendall** [comment]
For information about CamVid you should contact the authors directly. I'd recommend you use the data which I've packaged in the tutorial repo [here](https://github.com/alexgkendall/SegNet-Tutorial).

You should also use the model architectures specified in the [tutorial](http://mi.eng.cam.ac.uk/projects/segnet/tutorial.html) and follow the steps I've outlined there.

Thanks.

**Comment by etienne87** [comment]
Oh I didn't see this link. Thanks a lot!
